### ISSUE TITLE
Proposal: global overrides

### ISSUE THREAD

**Issue by adrifmonte** [rhberro/the-fake-backend#33]
We could have an `overrides` option in the server configuration, it would be useful to configure some failure use cases. At the moment, it already has some reusable overrides, but the routes still need to have them listed there. With those options in the server `overrides`, we could choose them in console for any route. As a suggestion, they could come in the end of the list with a `(global)` prefix.

**Comment by adrifmonte** [comment]
Duplicated issue:
https://github.com/rhberro/the-fake-backend/issues/32

**Comment by rhberro** [comment]
I really liked it! It would remove some duplicate lines. :partying_face:
