### ISSUE TITLE
Ts-node-dev could be used instead of the nodemon

### ISSUE THREAD

**Issue by luccasfraga** [rhberro/the-fake-backend#40]
I did a test using Ts-node-dev.

It has all native ts configurations.

https://www.npmjs.com/package/ts-node-dev

I think it gets better, right?

**Comment by fsmaia** [comment]
Amazing idea, however, I think it applies to the project usages because start scripts don't belong here :)

**Comment by fsmaia** [comment]
This would be applied to this project only if we document a complete usage scenario (a section in README or a example folder), otherwise, we should close this issue IMHO.

**Comment by rhberro** [comment]
I agree with you @fsmaia , this is related to the project usages, closing this issue for now.
