### ISSUE TITLE
Data containing number properties aren't properly handled

### ISSUE THREAD

**Issue by lpfjustino** [rhberro/the-fake-backend#43]
If the fixture contains a number in its root attributes or if a number is sent on the `data` property, Express interprets it as the status code and crashes. E.g.

```
  {
    path: '/distance',
    methods: [
      {
        type: MethodType.GET,
        data: 1000
      }
    ]
  }
```

Ideally we should parse as String the mock's content when it's sent.

**Comment by fsmaia** [comment]
Nice catch! This is the exact line that should be changed:
https://github.com/rhberro/the-fake-backend/blob/554a7f47a8a47c1766c864f3fcc8cf11b33886ee/source/server.ts#L156

IMHO I would check if the content is a number and then would stringify it. Dunno it parsing any response as string would bring some harm.
