### ISSUE TITLE
Unable to send response body when defining a override with a non-success status code

### ISSUE THREAD

**Issue by fernando-msj** [rhberro/the-fake-backend#44]
While defining overloads, the user is unable to define a response body for an override with a status code outside of the `[200..299]` range, for example:

```module.exports = [
  {
    path: '/test',
    methods: [
      {
        type: 'get',
        data: { successful: true },
        overrides: [
          {
            name: 'Random Error',
            code: 500,
            data: { successful: false },
          },
        ],
      },
    ],
  },
];
```

If the `Random Error` override is the selected one, requests to `/test` won't return a response body.

After investigating for a bit the issue appears to be in the  `createMethodResponse` function at  [`source/server.ts`](https://github.com/rhberro/the-fake-backend/blob/master/source/server.ts#L182-L189):

https://github.com/rhberro/the-fake-backend/blob/554a7f47a8a47c1766c864f3fcc8cf11b33886ee/source/server.ts#L182-L189

Wich as we can see, won't send a response body for an unsuccessful status code.

Initially, I thought I'd just remove the `if` statement and call it a fix, but as pointed by @nolleto this introduces a problem wherein cases like this one...

```module.exports = [
  {
    path: '/test',
    methods: [
      {
        type: 'get',
        data: { successful: true },
        overrides: [
          {
            name: 'Error',
            code: 500,
          },
        ],
      },
    ],
  },
];
```

...requests to the `/test` endpoint, while the `Error` override is selected, would also return the `{ successful: true }` in the response body, this happens because we [merge the base method with the selected override](https://github.com/rhberro/the-fake-backend/blob/master/source/server.ts#L59-L72), and returning successful response bodies in error responses would be undesirable in most cases IMHO.

On for how we could fix this issue, [this small patch](https://gist.github.com/fernando-msj/20145754b4e016b0caf9a9b044c6fdce) seems to work fine, but it kinda contradicts the way the overrides are supposed to work (In the sense that users expect overrides to _inherit_ all properties from the base request, even data, delay, and headers, which would now be an exception).

Another solution that I discussed with @nolleto was that users would need to add a `data: null` when they don't want to send a response body in the error response (with could be most of the cases) like this:

```
      {
        type: 'get',
        data: { successful: true },
        overrides: [
          {
            name: 'Error',
            code: 500,
            data: null
          },
        ],
      }
```

While this also works, it is a breaking change (one could argue that its is also annoying).

Any ideas on how to fix this?

**Comment by fsmaia** [comment]
@nolleto, about #7.

**Comment by nolleto** [comment]
I was thinking about this and I prefer the second scenario where the breaking change happens. 

IMHO, I don't like the idea to add an exception on overrides to check when status code is an error one send `data: null`. This is a behave that the one who implemented the route should control 100%.
So, if in your `Error 500` override should not return the `data` you should set it.

```js
      {
        type: 'get',
        data: { successful: true },
        overrides: [
          {
            name: 'Error',
            code: 500,
            data: null
          },
        ],
      }
```

**Comment by fsmaia** [comment]
Totally agree about setting data:null to reset :)
