### ISSUE TITLE
Error on PUT and POST method

### ISSUE THREAD

**Issue by diogoteodoro** [rhberro/the-fake-backend#50]
When  I send request from the browser using **the-fake-backend**  like a proxy, I receive this error:

`[HPM] Error occurred while trying to proxy request {endpoint} from localhost:8081 to {proxy} (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

GET method works normally.

**Comment by fsmaia** [comment]
Possibly related:
* https://github.com/chimurai/http-proxy-middleware/issues/171
* https://github.com/chimurai/http-proxy-middleware/issues/40

**Comment by fsmaia** [comment]
@rhberro, any news on this?

**Comment by rhberro** [comment]
@diogoteodoro is this still happening? Should I work on this?

**Comment by fsmaia** [comment]
Just found the solution, among with @jaehnri
