### ISSUE TITLE
Dynamic Params broken between v3.2.1 and v3.5.2

### ISSUE THREAD

**Issue by slimandslam** [rhberro/the-fake-backend#74]
This works fine in v3.2.1

```
 {
    path: '/question/:col',
    methods: [
      {
        type: 'get',
        file: (req) => `data/question/init-${req.params.col}.json`
      },
    ],
  },
```

In v3.5.0 it returns a 404
In v3.5.2 it returns. "You probably forgot to create the fallback fixture file /question/:col Error: Fixture not found"

**Comment by fsmaia** [comment]
Just found out that `req.params` isn't available on Express middlewares:
https://github.com/expressjs/express/issues/2088

**Comment by fsmaia** [comment]
@slimandslam sorry for taking so long! could you double check the fix?
