### ISSUE TITLE
Export all types

### ISSUE THREAD

**Issue by nolleto** [rhberro/the-fake-backend#8]
You could export all types to use it to create routes, for example:

```ts
// some-file.ts
import { Route } from 'the-fake-backend'

const routes: Route[] = [
  {
    path: "/my/endpoint",
    methods: [
      {
        type: "get",
        file: 'data/foo.json'
      },
    ],
  },
];

export default routes;
```

Currently, `Route` is not exported so, I can not use it 😢

**Comment by fsmaia** [comment]
Amazing. Additionally, I was thinking about export an enumerator with HTTP methods :)
