### ISSUE TITLE
Add response delay support

### ISSUE THREAD

**Issue by fsmaia** [rhberro/the-fake-backend#9]
It would be nice to support a delay timeout flag in endpoints, emulating that someones may have a slow response time.

**Comment by rhberro** [comment]
Did not get the idea, isn't throttling enough?

**Comment by nolleto** [comment]
Maybe we can add the property `throttling` into `MethodProperties`
```diff
export default interface MethodProperties {
  code?: number,
  data?: any,
  file?: string,
  paginated?: boolean,
  search?: Search,
+  throttling?: number,
}
```
And use like this:
```ts
import { Route } from './interfaces'

const myRoute: Route = {
  path: '/my/endpoint',
  methods: [
    {
      type: 'get',
      file: 'data/some/file',
      throttling: 1000,
    },
    {
      type: 'post',
      file: 'data/some/file',
      overrides: [
        {
          name: 'With throttling',
          throttling: 1000
        }
      ]
    }
  ]
}
```

What do you think?

**Comment by fsmaia** [comment]
Yep, although the throttling engine would be applied, from an end-user perspective throttling means a poor internet connection, and in this scenario, we want to emulate slow processing endpoints.
